project_id = "ufsacawxjkeokbfkdgrj"

[functions.analyze-ticket]
verify_jwt = false

[functions.analyze-receipt]
verify_jwt = false

[functions.business-chat]
verify_jwt = false

[functions.analyze-import]
verify_jwt = false

[functions.auth-login]
verify_jwt = false

[functions.auth-verify]
verify_jwt = false

[functions.auth-hash-password]
verify_jwt = false

[functions.analyze-sales-pdf]
verify_jwt = false
