project_id = "ufsacawxjkeokbfkdgrj"

[functions.analyze-ticket]
verify_jwt = false

[functions.analyze-receipt]
verify_jwt = false

[functions.business-chat]
verify_jwt = false

[functions.analyze-import]
verify_jwt = false
